# Generated by Django 4.2.1 on 2024-03-08 13:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Admin', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='enquiry',
            name='date',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
